import Testing
@testable import ESWCompilerLib

/// Full pipeline helper: source → tokens → trim → parse assigns → resolve components → generate.
private func generate(
    _ source: String,
    filename: String = "test.esw",
    sourceFile: String = "Sources/App/Views/test.esw",
    emitSourceLocations: Bool = false
) throws -> String {
    var tokenizer = Tokenizer(source: source, file: sourceFile)
    let rawTokens = try tokenizer.tokenize()
    let trimmedTokens = WhitespaceTrimmer.trim(rawTokens)
    let parameters = try AssignsParser.parse(tokens: trimmedTokens, file: sourceFile)
    let bodyTokens = trimmedTokens.filter {
        if case .assigns = $0 { return false }
        return true
    }
    let renderNodes = try ComponentResolver.resolve(bodyTokens)
    let generator = CodeGenerator(
        renderNodes: renderNodes,
        parameters: parameters,
        sourceFile: sourceFile,
        filename: filename,
        emitSourceLocations: emitSourceLocations
    )
    return generator.generate()
}

@Suite("CodeGenerator")
struct CodeGeneratorTests {

    @Test func simpleTextOnly() throws {
        let output = try generate("<h1>Hello</h1>", filename: "hello.esw")
        #expect(output.contains("func renderHello() -> String {"))
        #expect(output.contains("<h1>Hello</h1>"))
        #expect(output.contains("return _buf.finalize()"))
    }

    @Test func withOutputTag() throws {
        let output = try generate("<p><%= name %></p>", filename: "greeting.esw")
        #expect(output.contains("_buf.appendEscaped(name)"))
    }

    @Test func withRawOutputTag() throws {
        let output = try generate("<%== rawHTML %>", filename: "raw.esw")
        #expect(output.contains("_buf.appendUnsafe(rawHTML)"))
        #expect(!output.contains("ESW.escape"))
    }

    @Test func withCodeTag() throws {
        let output = try generate("<% if true { %>\nhello\n<% } %>", filename: "cond.esw")
        #expect(output.contains("if true {"))
        #expect(output.contains("}"))
    }

    @Test func commentsOmitted() throws {
        let output = try generate("<%# secret comment %>hello", filename: "test.esw")
        #expect(!output.contains("secret comment"))
        #expect(output.contains("hello"))
    }

    @Test func withAssigns() throws {
        let output = try generate("<%!\nvar user: User\nvar posts: [Post]\n%>\n<h1><%= user.name %></h1>", filename: "profile.esw")
        #expect(output.contains("func renderProfile("))
        #expect(output.contains("user: User"))
        #expect(output.contains("posts: [Post]"))
        #expect(output.contains("-> String"))
    }

    @Test func withDefaultValue() throws {
        let output = try generate("<%!\nvar isAdmin: Bool = false\n%>\nhello", filename: "test.esw")
        #expect(output.contains("isAdmin: Bool = false"))
    }

    @Test func noAssignsNoParams() throws {
        let output = try generate("hello", filename: "simple.esw")
        #expect(output.contains("func renderSimple() -> String {"))
    }

    @Test func sourceLocationsEmitted() throws {
        let output = try generate("<%= x %>", filename: "test.esw", emitSourceLocations: true)
        #expect(output.contains("#sourceLocation(file:"))
        #expect(output.contains("#sourceLocation()"))
    }

    @Test func sourceLocationsOmitted() throws {
        let output = try generate("<%= x %>", filename: "test.esw", emitSourceLocations: false)
        #expect(!output.contains("#sourceLocation"))
    }

    @Test func headerPresent() throws {
        let output = try generate("hello", filename: "test.esw", sourceFile: "Sources/App/Views/test.esw")
        #expect(output.contains("// AUTO-GENERATED by swift-esw. DO NOT EDIT."))
        #expect(output.contains("// Source: Sources/App/Views/test.esw"))
        #expect(!output.contains("import Nexus"))
        #expect(output.contains("import ESW"))
    }

    @Test func mixedContent() throws {
        let source = """
        <%!
        var user: User
        %>
        <div>
          <h1><%= user.name %></h1>
          <% if user.isAdmin { %>
            <span>Admin</span>
          <% } %>
        </div>
        """
        let output = try generate(source, filename: "user.esw")
        #expect(output.contains("func renderUser("))
        #expect(output.contains("user: User"))
        #expect(output.contains("_buf.appendEscaped(user.name)"))
        #expect(output.contains("if user.isAdmin {"))
        #expect(output.contains("}"))
    }

    @Test func connAsRegularParam() throws {
        let source = """
        <%!
        var conn: Connection
        var title: String
        %>
        <h1><%= title %></h1>
        """
        let output = try generate(source, filename: "page.esw")
        // conn declared as assign becomes a regular typed parameter
        #expect(output.contains("conn: Connection"))
        #expect(output.contains("title: String"))
        #expect(output.contains("-> String"))
    }

    @Test func doubleExtensionFunctionName() throws {
        let output = try generate("<h1>Hi</h1>", filename: "index.html.esw")
        #expect(output.contains("func renderIndex("))
    }
}
