/// A typed template. Its implementation is generated by ESWBuildPlugin.
/// The output is String for HTML/text or ESWLiveRender for `.live.hesw`.
public protocol ESWView {
    /// The generated renderer's result: normally `String` or ``ESWLiveRender``.
    associatedtype Output
    /// Renders the view's properties through its associated template.
    func render() -> Output
}
