/// Emits Swift from a resolved render tree and parsed template declarations.
/// Prefer the top-level compile functions when starting from template text.
public struct CodeGenerator {
    private let renderNodes: [RenderNode]
    private let parameters: [Parameter]
    private let sourceFile: String
    private let filename: String
    private let emitSourceLocations: Bool
    private let imports: [String]
    private let view: TemplateView?
    private let generatedBufferName: String
    private let slotValueName: String
    private let keyedBufferName: String

    /// Creates a generator for a previously parsed and resolved template.
    /// Logical filenames control generated names and the `.live.hesw` return type.
    public init(
        renderNodes: [RenderNode],
        parameters: [Parameter],
        sourceFile: String,
        filename: String,
        emitSourceLocations: Bool = true,
        imports: [String] = [],
        view: TemplateView? = nil
    ) {
        self.renderNodes = renderNodes
        self.parameters = parameters
        self.sourceFile = sourceFile
        self.filename = filename
        self.emitSourceLocations = emitSourceLocations
        self.imports = imports
        self.view = view
        let source = Self.sourceText(nodes: renderNodes, parameters: parameters)
        self.generatedBufferName = Self.freshIdentifier("_buf", avoiding: source)
        self.slotValueName = Self.freshIdentifier("__esw_slot_value", avoiding: source)
        self.keyedBufferName = Self.freshIdentifier("__esw_rows", avoiding: source)
    }

    /// Returns a self-contained immediately-invoked closure expression that
    /// builds and returns the rendered template buffer.
    public func generateExpression(live: Bool = false) -> String {
        var lines: [String] = []
        let bufferName = generatedBufferName
        lines.append("{")
        lines.append("    var \(bufferName) = \(live ? "ESWLiveBuffer" : "ESWBuffer")()")
        let emittedLocation = emitNodeBody(&lines, nodes: renderNodes, bufferName: bufferName)
        if emitSourceLocations && emittedLocation {
            lines.append("    #sourceLocation()")
        }
        lines.append("    return \(bufferName).finalize()")
        lines.append("}()")
        return lines.joined(separator: "\n")
    }

    /// Emits imports and a named renderer, or an extension for a supplied typed view.
    public func generate() -> String {
        var lines: [String] = []

        lines.append("// AUTO-GENERATED by swift-esw. DO NOT EDIT.")
        lines.append("// Source: \(sourceFile)")
        lines.append("")

        lines.append("import ESW")

        lines.append(contentsOf: imports.filter { $0 != "import ESW" })
        // Compatibility for existing Peregrine generators. Explicit imports
        // take precedence; arbitrary type names never select a framework.
        if imports.isEmpty, parameters.contains(where: { $0.type == "Connection" }) {
            lines.append("import Nexus")
        }

        lines.append("")

        if let view {
            lines.append("extension \(view.typeName) {")
            lines.append("    \(view.accessModifier)func render() -> \(returnType) {")
            var body: [String] = []
            generateRenderBody(&body)
            lines.append(contentsOf: body.map { "    " + $0 })
            lines.append("    }")
            lines.append("}")
        } else {
            generateStringFunction(&lines)
        }
        if view == nil, Naming.isPartial(filename) {
            lines.append("")
            lines.append("func \(Naming.bufferFunctionName(from: filename))(\(buildParamList())) -> \(returnType) {")
            let arguments = parameters.map {
                let name = Self.escapedParamName($0.name.replacingHyphens())
                return "\(name): \(name)"
            }.joined(separator: ", ")
            lines.append("    \(Naming.functionName(from: filename))(\(arguments))")
            lines.append("}")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private func generateStringFunction(_ lines: inout [String]) {
        let funcName = Naming.functionName(from: filename)
        let paramList = buildParamList()
        if paramList.isEmpty {
            lines.append("func \(funcName)() -> \(returnType) {")
        } else {
            lines.append("func \(funcName)(")
            lines.append("    \(paramList)")
            lines.append(") -> \(returnType) {")
        }
        generateRenderBody(&lines)
        lines.append("}")
    }

    private func generateRenderBody(_ lines: inout [String]) {
        let bufferName = generatedBufferName
        lines.append("    var \(bufferName) = \(isLiveFile ? "ESWLiveBuffer" : "ESWBuffer")()")
        let emittedLocation = emitNodeBody(&lines, nodes: renderNodes, bufferName: bufferName)
        if emitSourceLocations && emittedLocation {
            lines.append("#sourceLocation()")
        }
        lines.append("    return \(bufferName).finalize()")
    }

    private var isLiveFile: Bool { TemplateSyntax.isLive(path: filename) }
    private var returnType: String { isLiveFile ? "ESWLiveRender" : "String" }

    private func buildParamList() -> String {
        return parameters.map { param in
            let swiftKey = param.name.split(separator: "-", omittingEmptySubsequences: false).joined(separator: "_")
            let escapedKey = CodeGenerator.escapedParamName(swiftKey)
            let type = param.type
            if let defaultValue = param.defaultValue {
                return "\(escapedKey): \(type) = \(defaultValue)"
            } else {
                return "\(escapedKey): \(type)"
            }
        }.joined(separator: ", ")
    }

    @discardableResult
    private func emitNodeBody(_ lines: inout [String], nodes: [RenderNode], bufferName: String) -> Bool {
        var emittedLocation = false
        for node in nodes {
            switch node {
            case .token(let token):
                if emitTokenBody(&lines, token: token, bufferName: bufferName) { emittedLocation = true }
            case .component(let componentNode):
                if emitComponentNode(&lines, node: componentNode, bufferName: bufferName) { emittedLocation = true }
            }
        }
        return emittedLocation
    }

    @discardableResult
    private func emitComponentNode(_ lines: inout [String], node: ComponentNode, bufferName: String) -> Bool {
        let emittedLocation = emitSourceLocation(lines: &lines, node.metadata)
        let directives = emitDirectives(&lines, attributes: node.attributes, bufferName: bufferName)
        let attributes = node.attributes.filter { !$0.key.hasPrefix(":") }.map(componentArgument)
        let slots = Dictionary(grouping: node.namedSlots, by: \.name).sorted { $0.key < $1.key }
        let hasSlots = !slots.isEmpty || !node.defaultSlot.isEmpty
        let callee = componentCallee(node.name)
        if !hasSlots {
            lines.append("    \(bufferName).appendUnsafe(\(callee)(\(attributes.joined(separator: ", "))))")
        } else {
            lines.append("    \(bufferName).appendUnsafe(\(callee)(")
            for attribute in attributes { lines.append("        \(attribute),") }
            for (index, group) in slots.enumerated() {
                let comma = index < slots.count - 1 || !node.defaultSlot.isEmpty ? "," : ""
                let key = group.key.replacingHyphens()
                if group.value.count == 1, let slot = group.value.first, slot.attributes.isEmpty {
                    lines.append("        \(key): {")
                    emitContent(&lines, nodes: slot.nodes)
                    lines.append("        }()\(comma)")
                } else {
                    lines.append("        \(key): ESW.slots {")
                    for slot in group.value { emitSlotEntry(&lines, slot: slot) }
                    lines.append("        }\(comma)")
                }
            }
            if !node.defaultSlot.isEmpty {
                if let binding = TemplateValidation.binding(in: node.attributes) {
                    lines.append("        content: { \(slotValueName) in")
                    lines.append("            let \(binding) = \(slotValueName)")
                    emitContent(&lines, nodes: node.defaultSlot)
                    lines.append("        }")
                } else {
                    lines.append("        content: {")
                    emitContent(&lines, nodes: node.defaultSlot)
                    lines.append("        }()")
                }
            }
            lines.append("    ))")
        }
        lines.append(contentsOf: directives)
        return emittedLocation
    }

    private func emitContent(_ lines: inout [String], nodes: [RenderNode]) {
        let bufferName = generatedBufferName
        lines.append("            var \(bufferName) = ESWBuffer()")
        emitNodeBody(&lines, nodes: nodes, bufferName: bufferName)
        lines.append("            return \(bufferName).finalize()")
    }

    private func emitSlotEntry(_ lines: inout [String], slot: Slot) {
        emitSourceLocation(lines: &lines, slot.metadata)
        let directives = emitDirectives(&lines, attributes: slot.attributes, bufferName: generatedBufferName)
        let arguments = slot.attributes.filter { !$0.key.hasPrefix(":") }.map(componentArgument).joined(separator: ", ")
        let binding = TemplateValidation.binding(in: slot.attributes)
        lines.append("            ESWSlot(attributes: .init(\(arguments))) { \(binding == nil ? "_" : slotValueName) in")
        if let binding { lines.append("                let \(binding) = \(slotValueName)") }
        emitContent(&lines, nodes: slot.nodes)
        lines.append("            }")
        lines.append(contentsOf: directives)
    }

    private func componentCallee(_ name: String) -> String {
        name.contains(".") ? name : kebabToPascalCase(name) + ".render"
    }

    private func componentArgument(_ attribute: ComponentAttribute) -> String {
        let name = attribute.key.replacingHyphens()
        switch attribute.value {
        case .none: return "\(name): true"
        case .string(let value): return "\(name): \(Self.rawStringLiteral(value))"
        case .expression(let value): return "\(name): \(value)"
        }
    }

    @discardableResult
    private func emitTokenBody(_ lines: inout [String], token: Token, bufferName: String) -> Bool {
        var emittedLocation = false
        switch token {
        case .text(let s, let meta):
            if !s.isEmpty {
                // #sourceLocation() inside a multiline string literal is a syntax error
                if !s.contains("\n") {
                    if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
                }
                if s.contains("\n") {
                    let h = Self.rawStringHashes(s)
                    lines.append("    \(bufferName).append(\(h)\"\"\"\n\(s)\n\"\"\"\(h))")
                } else {
                    lines.append("    \(bufferName).append(\(Self.rawStringLiteral(s)))")
                }
            }
        case .output(let expr, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(bufferName).appendEscaped(\(expr))")
        case .rawOutput(let expr, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(bufferName).appendUnsafe(\(expr))")
        case .htmlAttribute(let name, let expression, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(bufferName).appendUnsafe(ESW.attribute(\(Self.rawStringLiteral(name)), \(expression)))")
        case .htmlAttributes(let expression, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(bufferName).appendUnsafe(ESW.attributes(\(expression)))")
        case .keyedOpen(let loop, let key, let condition, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            emitKeyedOpening(&lines, loop: loop, key: key, condition: condition, bufferName: bufferName)
        case .keyedClose(let conditional, _):
            lines.append(contentsOf: keyedClosing(conditional: conditional))
        case .code(let code, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(code)")
        case .comment, .assigns, .componentClose, .slotOpen, .slotClose:
            break
        case .componentTag(let name, let attributes, _, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            let callee = componentCallee(name)
            let directives = emitDirectives(&lines, attributes: attributes, bufferName: bufferName)
            let argList = buildComponentArgList(attributes)
            lines.append("    \(bufferName).appendUnsafe(\(callee)(\(argList)))")
            lines.append(contentsOf: directives)
        }
        return emittedLocation
    }

    // MARK: - Component helpers

    private func emitDirectives(_ lines: inout [String], attributes: [ComponentAttribute], bufferName: String) -> [String] {
        func expression(_ key: String) -> String? {
            guard let attribute = attributes.first(where: { $0.key == key }),
                  case .expression(let value) = attribute.value else { return nil }
            return value
        }
        if let key = expression(":key"), let loop = expression(":for") {
            let condition = expression(":if")
            emitKeyedOpening(&lines, loop: loop, key: key, condition: condition, bufferName: bufferName)
            return keyedClosing(conditional: condition != nil)
        }
        var count = 0
        for (key, keyword) in [(":for", "for"), (":if", "if")] {
            if let attribute = attributes.first(where: { $0.key == key }), case .expression(let expression) = attribute.value {
                lines.append("    \(keyword) \(expression) {")
                count += 1
            }
        }
        return Array(repeating: "    }", count: count)
    }

    private func emitKeyedOpening(_ lines: inout [String], loop: String, key: String, condition: String?, bufferName: String) {
        lines.append("    \(bufferName).appendKeyed { \(keyedBufferName) in")
        lines.append("    for \(loop) {")
        if let condition { lines.append("    if \(condition) {") }
        lines.append("    \(keyedBufferName).append(key: \(key)) { \(bufferName) in")
    }

    private func keyedClosing(conditional: Bool) -> [String] {
        Array(repeating: "    }", count: conditional ? 4 : 3)
    }

    private func kebabToPascalCase(_ name: String) -> String {
        name.split(separator: "-", omittingEmptySubsequences: true)
            .map { segment -> String in
                let s = String(segment)
                guard let first = s.first else { return s }
                return first.uppercased() + s.dropFirst()
            }
            .joined()
    }

    private func buildComponentArgList(_ attributes: [ComponentAttribute]) -> String {
        attributes.filter { !$0.key.hasPrefix(":") }.map(componentArgument).joined(separator: ", ")
    }

    // MARK: - Private helpers

    /// A conservative source scan keeps generated locals out of the caller's
    /// namespace, including parameters, EEx code, directives, and nested slots.
    private static func sourceText(nodes: [RenderNode], parameters: [Parameter]) -> String {
        var fragments = parameters.flatMap { [$0.name, $0.type, $0.defaultValue ?? ""] }
        func attributes(_ values: [ComponentAttribute]) {
            for attribute in values {
                fragments.append(attribute.key)
                switch attribute.value {
                case .string(let value), .expression(let value): fragments.append(value)
                case .none: break
                }
            }
        }
        func visit(_ nodes: [RenderNode]) {
            for node in nodes {
                switch node {
                case .component(let component):
                    fragments.append(component.name)
                    attributes(component.attributes)
                    visit(component.defaultSlot)
                    for slot in component.namedSlots {
                        fragments.append(slot.name)
                        attributes(slot.attributes)
                        visit(slot.nodes)
                    }
                case .token(let token):
                    switch token {
                    case .text(let value, _), .output(let value, _), .rawOutput(let value, _),
                         .code(let value, _), .comment(let value, _), .assigns(let value, _),
                         .htmlAttributes(let value, _): fragments.append(value)
                    case .htmlAttribute(let name, let expression, _): fragments += [name, expression]
                    case .keyedOpen(let loop, let key, let condition, _): fragments += [loop, key, condition ?? ""]
                    case .keyedClose: break
                    case .componentTag(let name, let values, _, _), .slotOpen(let name, let values, _, _):
                        fragments.append(name)
                        attributes(values)
                    case .componentClose(let name, _), .slotClose(let name, _): fragments.append(name)
                    }
                }
            }
        }
        visit(nodes)
        return fragments.joined(separator: "\n")
    }

    private static func freshIdentifier(_ base: String, avoiding source: String) -> String {
        var name = base
        var suffix = 0
        while source.contains(name) {
            suffix += 1
            name = base + String(suffix)
        }
        return name
    }

    static func rawStringHashes(_ s: String) -> String {
        var hashes = 1
        while s.contains("\"" + String(repeating: "#", count: hashes)) ||
              s.contains(String(repeating: "#", count: hashes) + "\"") ||
              s.contains("\\" + String(repeating: "#", count: hashes)) {
            hashes += 1
        }
        while s.contains("\"\"\"" + String(repeating: "#", count: hashes)) {
            hashes += 1
        }
        return String(repeating: "#", count: hashes)
    }

    static func rawStringLiteral(_ s: String) -> String {
        let h = rawStringHashes(s)
        if s.contains("\n") { return "\(h)\"\"\"\n\(s)\n\"\"\"\(h)" }
        return "\(h)\"\(s)\"\(h)"
    }

    private static let swiftKeywords: Set<String> = [
        "class", "struct", "enum", "protocol", "func", "var", "let",
        "import", "return", "if", "else", "for", "while", "switch",
        "case", "default", "break", "continue", "in", "is", "as",
        "self", "Self", "true", "false", "nil", "try", "catch",
        "throw", "throws", "guard", "where", "init", "deinit",
        "extension", "subscript", "operator", "typealias",
    ]

    static func escapedParamName(_ name: String) -> String {
        swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    @discardableResult
    private func emitSourceLocation(lines: inout [String], _ meta: Metadata) -> Bool {
        guard emitSourceLocations else { return false }
        lines.append("#sourceLocation(file: \(String(reflecting: meta.file)), line: \(meta.line))")
        return true
    }
}

extension String {
    func replacingHyphens() -> String {
        split(separator: "-", omittingEmptySubsequences: false).joined(separator: "_")
    }
}
