public struct CodeGenerator {
    private let tokens: [Token]
    private let parameters: [Parameter]
    private let sourceFile: String
    private let filename: String
    private let emitSourceLocations: Bool

    public init(
        tokens: [Token],
        parameters: [Parameter],
        sourceFile: String,
        filename: String,
        emitSourceLocations: Bool = true
    ) {
        self.tokens = tokens
        self.parameters = parameters
        self.sourceFile = sourceFile
        self.filename = filename
        self.emitSourceLocations = emitSourceLocations
    }

    /// Returns a self-contained immediately-invoked closure expression that
    /// builds and returns the rendered template buffer.
    ///
    /// Use this for macro expansion (`#render`, `#esw`) where you need a
    /// `String`-typed expression rather than a named function declaration.
    /// Source location directives are omitted — the closure is inlined at the
    /// call site, so the call site itself is the error location.
    ///
    /// ```swift
    /// // Expands to something like:
    /// // {
    /// //     var _buf = ""
    /// //     _buf += "<ul>"
    /// //     for item in items { _buf += ESW.escape(item) }
    /// //     _buf += "</ul>"
    /// //     return _buf
    /// // }()
    /// ```
    public func generateExpression() -> String {
        var lines: [String] = []
        lines.append("{")
        lines.append("    var _buf = \"\"")
        let emittedLocation = emitTokenBody(&lines)
        if emitSourceLocations && emittedLocation {
            lines.append("    #sourceLocation()")
        }
        lines.append("    return _buf")
        lines.append("}()")
        return lines.joined(separator: "\n")
    }

    public func generate() -> String {
        let isPartial = Naming.isPartial(filename)
        var lines: [String] = []

        lines.append("// AUTO-GENERATED by swift-esw. DO NOT EDIT.")
        lines.append("// Source: \(sourceFile)")
        lines.append("")
        lines.append("import Nexus")
        lines.append("import ESW")
        lines.append("")

        if isPartial {
            // Buffer-returning variant (for embedding in parent templates)
            generateBufferFunction(&lines)
            lines.append("")
            // Connection-returning variant (calls buffer variant)
            generateConnFunctionCallingBuffer(&lines)
        } else {
            // Standard Connection-returning function
            generateConnFunction(&lines)
        }

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Generation methods

    /// Standard Connection-returning function with inline buffer building.
    private func generateConnFunction(_ lines: inout [String]) {
        let funcName = Naming.functionName(from: filename)
        let paramList = buildParamList(includeConn: true)
        lines.append("func \(funcName)(")
        lines.append("    \(paramList)")
        lines.append(") -> Connection {")
        lines.append("    var _buf = \"\"")
        let emittedLocation = emitTokenBody(&lines)
        if emitSourceLocations && emittedLocation {
            lines.append("#sourceLocation()")
        }
        lines.append("    return conn.html(_buf)")
        lines.append("}")
    }

    /// Buffer-returning variant for partials: `func _renderXBuffer(...) -> String`
    private func generateBufferFunction(_ lines: inout [String]) {
        let bufferName = Naming.bufferFunctionName(from: filename)
        let paramList = buildParamList(includeConn: false)
        if paramList.isEmpty {
            lines.append("func \(bufferName)() -> String {")
        } else {
            lines.append("func \(bufferName)(")
            lines.append("    \(paramList)")
            lines.append(") -> String {")
        }
        lines.append("    var _buf = \"\"")
        let emittedLocation = emitTokenBody(&lines)
        if emitSourceLocations && emittedLocation {
            lines.append("#sourceLocation()")
        }
        lines.append("    return _buf")
        lines.append("}")
    }

    /// Connection-returning wrapper that delegates to the buffer variant.
    private func generateConnFunctionCallingBuffer(_ lines: inout [String]) {
        let funcName = Naming.functionName(from: filename)
        let bufferName = Naming.bufferFunctionName(from: filename)
        let connParamList = buildParamList(includeConn: true)
        lines.append("func \(funcName)(")
        lines.append("    \(connParamList)")
        lines.append(") -> Connection {")

        let callArgs = parameters.map {
            let escaped = Self.escapedParamName($0.name)
            return "\(escaped): \(escaped)"
        }.joined(separator: ", ")
        lines.append("    return conn.html(\(bufferName)(\(callArgs)))")
        lines.append("}")
    }

    /// Emits the token body (shared between conn and buffer functions).
    /// Returns `true` if at least one `#sourceLocation(file:line:)` directive was emitted.
    @discardableResult
    private func emitTokenBody(_ lines: inout [String]) -> Bool {
        var emittedLocation = false
        for token in tokens {
            switch token {
            case .text(let s, let meta):
                if !s.isEmpty {
                    if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
                    if containsNewline(s) {
                        let h = rawStringHashes(s)
                        lines.append("    _buf += \(h)\"\"\"")
                        lines.append(s)
                        lines.append("\"\"\"\(h)")
                    } else {
                        lines.append("    _buf += \(rawStringLiteral(s))")
                    }
                }
            case .output(let expr, let meta):
                if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
                lines.append("    _buf += ESW.escape(\(expr))")
            case .rawOutput(let expr, let meta):
                if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
                lines.append("    _buf += \(expr)")
            case .code(let code, let meta):
                if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
                lines.append("    \(code)")
            case .comment, .assigns:
                break
            }
        }
        return emittedLocation
    }

    // MARK: - Private helpers

    private func buildParamList(includeConn: Bool) -> String {
        var parts: [String] = []
        if includeConn {
            parts.append("conn: Connection")
        }
        for param in parameters {
            let name = Self.escapedParamName(param.name)
            if let defaultValue = param.defaultValue {
                parts.append("\(name): \(param.type) = \(defaultValue)")
            } else {
                parts.append("\(name): \(param.type)")
            }
        }
        return parts.joined(separator: ",\n    ")
    }

    private func containsNewline(_ s: String) -> Bool {
        for c in s where c == "\n" { return true }
        return false
    }

    /// Returns the minimum hash string needed for a raw string literal of `s`.
    private func rawStringHashes(_ s: String) -> String {
        var hashes = 1
        while containsSubstring(s, "\"" + String(repeating: "#", count: hashes)) ||
              containsSubstring(s, String(repeating: "#", count: hashes) + "\"") {
            hashes += 1
        }
        // Multi-line raw strings also need to avoid """# collisions
        while containsSubstring(s, "\"\"\"" + String(repeating: "#", count: hashes)) {
            hashes += 1
        }
        return String(repeating: "#", count: hashes)
    }

    /// Wraps a single-line string in a raw string literal.
    private func rawStringLiteral(_ s: String) -> String {
        let h = rawStringHashes(s)
        return "\(h)\"\(s)\"\(h)"
    }

    private func containsSubstring(_ haystack: String, _ needle: String) -> Bool {
        guard !needle.isEmpty else { return true }
        var i = haystack.startIndex
        while i <= haystack.endIndex {
            let remaining = haystack[i...]
            guard remaining.count >= needle.count else { return false }
            if remaining.hasPrefix(needle) { return true }
            i = haystack.index(after: i)
        }
        return false
    }

    private static let swiftKeywords: Set<String> = [
        "class", "struct", "enum", "protocol", "func", "var", "let",
        "import", "return", "if", "else", "for", "while", "switch",
        "case", "default", "break", "continue", "in", "is", "as",
        "self", "Self", "true", "false", "nil", "try", "catch",
        "throw", "throws", "guard", "where", "init", "deinit",
        "extension", "subscript", "operator", "typealias",
        "associatedtype", "inout", "static", "public", "private",
        "internal", "fileprivate", "open", "mutating", "nonmutating",
        "override", "convenience", "required", "dynamic", "lazy",
        "final", "weak", "unowned", "some", "any",
    ]

    static func escapedParamName(_ name: String) -> String {
        swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    /// Emits a `#sourceLocation` directive if source locations are enabled.
    /// Returns `true` if a directive was emitted.
    @discardableResult
    private func emitSourceLocation(lines: inout [String], _ meta: Metadata) -> Bool {
        guard emitSourceLocations else { return false }
        lines.append("#sourceLocation(file: \"\(meta.file)\", line: \(meta.line))")
        return true
    }
}
